package com.training.communication;

public enum MessageType {
    REQUEST_LAST_NAME,
    REQUEST_FIRST_NAME,
    REQUEST_MIDDLE_NAME,
    REQUEST_NICK_NAME,
    REQUEST_COMMENT,
    REQUEST_USER_GROUP,
    REQUEST_HOME_PHONE,
    REQUEST_MOB_PHONE,
    REQUEST_MOB_PHONE_SECOND,
    REQUEST_EMAIL,
    REQUEST_SKYPE,
    REQUEST_INDEX,
    REQUEST_CITY,
    REQUEST_STREET,
    REQUEST_HOUSE_NUM,
    REQUEST_FLAT,
    WRONG_INPUT_VALUE
}
